import sqlite3
import pandas as pd
from dbname import sqldbname


sqlcommand = "SELECT \
'LTE' as Tech, \
 \
TABLE2.NE,TABLE2.CELLNAME,TABLE2.CELLID,TABLE2.SECTOREQMID,\
TABLE2.SECTOREQMANTENNA,InventoryBoard.FRAMENO,InventoryBoard.BoardName,InventoryBoard.ManufacturerData,InventoryBoard.ModuleType \
FROM \
(SELECT TABLE1.NE,TABLE1.CELLNAME,TABLE1.CELLID,TABLE1.SECTOREQMID,SECTOREQM.SECTOREQMANTENNA \
FROM(SELECT CELL.NE,CELL.CELLNAME,CELL.CELLID,SECTOREQMID FROM CELL \
LEFT JOIN EUCELLSECTOREQM ON CELL.NE= EUCELLSECTOREQM.NE AND CELL.CELLID=EUCELLSECTOREQM.LOCALCELLID) TABLE1 \
LEFT JOIN SECTOREQM ON TABLE1.NE=SECTOREQM.NE AND TABLE1.SECTOREQMID=SECTOREQM.SECTOREQMID)TABLE2 \
LEFT JOIN InventoryBoard ON TABLE2.NE=InventoryBoard.NE \
WHERE BoardName LIKE '%RRU%' AND instr(SECTOREQMANTENNA, frameNo)>0 \
 \
 \
 \
UNION \
 \
 \
 \
SELECT  \
'UMTS' as Tech, \
TABLE2.NE,TABLE2.CELLNAME,TABLE2.CELLID,TABLE2.SECTOREQMID,TABLE2.SECTOREQMANTENNA,InventoryBoard.FRAMENO,InventoryBoard.BoardName,InventoryBoard.ManufacturerData,InventoryBoard.ModuleType \
FROM \
(SELECT TABLE1.NE,TABLE1.CELLNAME,TABLE1.ULOCELLID CELLID,TABLE1.SECTOREQMID,SECTOREQM.SECTOREQMANTENNA \
FROM \
(SELECT DISTINCT ULOCELLSECTOREQM.NE,CELLNAME,ULOCELLID,SECTOREQMID FROM ULOCELLSECTOREQM \
INNER JOIN UCELL ON NODEBFUNCTIONNAME=NODEBNAME AND ULOCELLID=LOCELL) TABLE1 \
LEFT JOIN SECTOREQM ON TABLE1.NE=SECTOREQM.NE AND TABLE1.SECTOREQMID=SECTOREQM.SECTOREQMID)TABLE2 \
LEFT JOIN InventoryBoard ON TABLE2.NE=InventoryBoard.NE \
WHERE BoardName LIKE '%RRU%' AND instr(SECTOREQMANTENNA, frameNo)>0 \
UNION \
SELECT DISTINCT \
'GSM' as Tech, \
T4.NE,T4.CELLNAME,T4.CI CELLID,T4.SECTOREQMID,t4.SECTOREQMANTENNA,InventoryBoard.FRAMENO,InventoryBoard.BoardName,InventoryBoard.ManufacturerData,InventoryBoard.ModuleType \
FROM \
(SELECT T3.NE,T3.CELLNAME,T3.CI,T3.GTRXGROUPID,T3.SECTOREQMID,SECTOREQM.SECTOREQMANTENNA \
FROM \
(SELECT T2.NE,T2.CELLNAME,T2.CI,T2.GTRXGROUPID,SECTOREQMID \
FROM \
(SELECT T1.NE,GCELL.CELLNAME,GCELL.CI,T1.GBTSFUNCTIONNAME,T1.GTRXGROUPID,T1.BTSID \
FROM \
(SELECT GTRXGROUP.NE,BTS.NE RNC,GLOCELLID,GBTSFUNCTIONNAME,GTRXGROUPID,BTSID FROM GTRXGROUP \
INNER JOIN BTS ON GTRXGROUP.GBTSFUNCTIONNAME=BTS.BTSNAME) T1 \
LEFT JOIN GCELL ON GCELL.BTSID=T1.BTSID AND GCELL.GLOCELLID=T1.GLOCELLID AND T1.RNC=GCELL.NE)T2 \
LEFT JOIN GTRXGROUPSECTOREQM ON T2.NE = GTRXGROUPSECTOREQM.NE AND T2.GTRXGROUPID=GTRXGROUPSECTOREQM.GTRXGROUPID)T3 \
LEFT JOIN SECTOREQM ON T3.NE=SECTOREQM.NE AND T3.SECTOREQMID=SECTOREQM.SECTOREQMID)T4 \
LEFT JOIN InventoryBoard ON T4.NE=InventoryBoard.NE \
WHERE BoardName LIKE '%RRU%' AND instr(SECTOREQMANTENNA, frameNo)>0"

conn = sqlite3.connect("imports/20230427.sqlite")
cur = conn.cursor()
df = pd.read_sql(sqlcommand, conn)
cur.close()

print(df.to_csv("result.csv"))